# -*- coding: utf-8 -*-
"""GPT-Based Client Strategy Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WxcTqMmPlAlqu7ZfqFWeHJLsY-0HOEf
"""

!pip install streamlit openai --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile strategy_generator.py
# import streamlit as st
# import openai
# 
# st.set_page_config(page_title="Client Strategy Generator", layout="centered")
# 
# st.title("GPT-Based Client Strategy Generator")
# st.markdown("Paste a client brief or business description. Get a strategic summary.")
# 
# # Input
# client_input = st.text_area("Client Brief", height=200, placeholder="Paste client notes or a raw business overview...")
# 
# # OpenAI API Key
# openai.api_key = st.secrets["OPENAI_API_KEY"]
# 
# if st.button("Generate Strategy") and client_input:
#     with st.spinner("Analyzing with GPT..."):
#         prompt = f"""
#         You are a management consultant. Analyze the following client brief and provide:
#         1. A 3-sentence executive summary
#         2. 5-point strategy recommendation
#         3. Bullet summary for a PowerPoint slide
# 
#         Client Input: {client_input}
#         """
# 
#         response = openai.ChatCompletion.create(
#             model="gpt-4",
#             messages=[{"role": "user", "content": prompt}],
#             temperature=0.7,
#             max_tokens=700
#         )
# 
#         result = response['choices'][0]['message']['content']
#         st.markdown("### 📋 Generated Strategy")
#         st.markdown(result)
#

import openai

client = openai.OpenAI(api_key="sk-...") ##open api key here

client_input = """
Our client is a mid-sized logistics company operating in the Midwest. Their core challenge is inefficiency in last-mile delivery due to outdated routing software and lack of real-time tracking. They want to expand into two new states within 6 months while reducing current delivery costs by at least 10%. Competitors have already implemented AI-based route optimization.
"""

prompt = f"""
You are a management consultant. Analyze the following client brief and provide:
1. A 3-sentence executive summary
2. 5-point strategy recommendation
3. Bullet summary for a PowerPoint slide

Client Input: {client_input}
"""

response = client.chat.completions.create(
    model="gpt-4",
    messages=[
        {"role": "user", "content": prompt}
    ],
    temperature=0.7,
    max_tokens=700
)

print(response.choices[0].message.content)

!pip install --upgrade openai